//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureDesk.DocumentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentData", Namespace="http://schemas.datacontract.org/2004/07/SecureDesk_WCF_Service.Models")]
    [System.SerializableAttribute()]
    public partial class DocumentData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sharedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileLink {
            get {
                return this.fileLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.fileLinkField, value) != true)) {
                    this.fileLinkField = value;
                    this.RaisePropertyChanged("fileLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fileNameField, value) != true)) {
                    this.fileNameField = value;
                    this.RaisePropertyChanged("fileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sharedBy {
            get {
                return this.sharedByField;
            }
            set {
                if ((object.ReferenceEquals(this.sharedByField, value) != true)) {
                    this.sharedByField = value;
                    this.RaisePropertyChanged("sharedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocumentService.IDocumentService")]
    public interface IDocumentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/DoWork", ReplyAction="http://tempuri.org/IDocumentService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/DoWork", ReplyAction="http://tempuri.org/IDocumentService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/connectToFirebase", ReplyAction="http://tempuri.org/IDocumentService/connectToFirebaseResponse")]
        bool connectToFirebase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/connectToFirebase", ReplyAction="http://tempuri.org/IDocumentService/connectToFirebaseResponse")]
        System.Threading.Tasks.Task<bool> connectToFirebaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/uploadDocument", ReplyAction="http://tempuri.org/IDocumentService/uploadDocumentResponse")]
        void uploadDocument(byte[] fileByte, string fileName, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/uploadDocument", ReplyAction="http://tempuri.org/IDocumentService/uploadDocumentResponse")]
        System.Threading.Tasks.Task uploadDocumentAsync(byte[] fileByte, string fileName, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/addDocument", ReplyAction="http://tempuri.org/IDocumentService/addDocumentResponse")]
        void addDocument(string link, string fileName, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/addDocument", ReplyAction="http://tempuri.org/IDocumentService/addDocumentResponse")]
        System.Threading.Tasks.Task addDocumentAsync(string link, string fileName, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/getAllDocumnetData", ReplyAction="http://tempuri.org/IDocumentService/getAllDocumnetDataResponse")]
        SecureDesk.DocumentService.DocumentData[] getAllDocumnetData(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/getAllDocumnetData", ReplyAction="http://tempuri.org/IDocumentService/getAllDocumnetDataResponse")]
        System.Threading.Tasks.Task<SecureDesk.DocumentService.DocumentData[]> getAllDocumnetDataAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/deleteDocument", ReplyAction="http://tempuri.org/IDocumentService/deleteDocumentResponse")]
        void deleteDocument(string email, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/deleteDocument", ReplyAction="http://tempuri.org/IDocumentService/deleteDocumentResponse")]
        System.Threading.Tasks.Task deleteDocumentAsync(string email, string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentServiceChannel : SecureDesk.DocumentService.IDocumentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentServiceClient : System.ServiceModel.ClientBase<SecureDesk.DocumentService.IDocumentService>, SecureDesk.DocumentService.IDocumentService {
        
        public DocumentServiceClient() {
        }
        
        public DocumentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public bool connectToFirebase() {
            return base.Channel.connectToFirebase();
        }
        
        public System.Threading.Tasks.Task<bool> connectToFirebaseAsync() {
            return base.Channel.connectToFirebaseAsync();
        }
        
        public void uploadDocument(byte[] fileByte, string fileName, string email) {
            base.Channel.uploadDocument(fileByte, fileName, email);
        }
        
        public System.Threading.Tasks.Task uploadDocumentAsync(byte[] fileByte, string fileName, string email) {
            return base.Channel.uploadDocumentAsync(fileByte, fileName, email);
        }
        
        public void addDocument(string link, string fileName, string email) {
            base.Channel.addDocument(link, fileName, email);
        }
        
        public System.Threading.Tasks.Task addDocumentAsync(string link, string fileName, string email) {
            return base.Channel.addDocumentAsync(link, fileName, email);
        }
        
        public SecureDesk.DocumentService.DocumentData[] getAllDocumnetData(string email) {
            return base.Channel.getAllDocumnetData(email);
        }
        
        public System.Threading.Tasks.Task<SecureDesk.DocumentService.DocumentData[]> getAllDocumnetDataAsync(string email) {
            return base.Channel.getAllDocumnetDataAsync(email);
        }
        
        public void deleteDocument(string email, string fileName) {
            base.Channel.deleteDocument(email, fileName);
        }
        
        public System.Threading.Tasks.Task deleteDocumentAsync(string email, string fileName) {
            return base.Channel.deleteDocumentAsync(email, fileName);
        }
    }
}
