//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureDesk.AuthenticateClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User Credentials", Namespace="http://schemas.datacontract.org/2004/07/SecureDesk_WCF_Service.Models")]
    [System.SerializableAttribute()]
    public partial class UserCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_Auth_EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_Auth_PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Auth_Email {
            get {
                return this.User_Auth_EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.User_Auth_EmailField, value) != true)) {
                    this.User_Auth_EmailField = value;
                    this.RaisePropertyChanged("User_Auth_Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Auth_Password {
            get {
                return this.User_Auth_PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.User_Auth_PasswordField, value) != true)) {
                    this.User_Auth_PasswordField = value;
                    this.RaisePropertyChanged("User_Auth_Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticateClient.IAuthService")]
    public interface IAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/validateLogin", ReplyAction="http://tempuri.org/IAuthService/validateLoginResponse")]
        bool validateLogin(SecureDesk.AuthenticateClient.UserCredentials authUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/validateLogin", ReplyAction="http://tempuri.org/IAuthService/validateLoginResponse")]
        System.Threading.Tasks.Task<bool> validateLoginAsync(SecureDesk.AuthenticateClient.UserCredentials authUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthServiceChannel : SecureDesk.AuthenticateClient.IAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceClient : System.ServiceModel.ClientBase<SecureDesk.AuthenticateClient.IAuthService>, SecureDesk.AuthenticateClient.IAuthService {
        
        public AuthServiceClient() {
        }
        
        public AuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool validateLogin(SecureDesk.AuthenticateClient.UserCredentials authUser) {
            return base.Channel.validateLogin(authUser);
        }
        
        public System.Threading.Tasks.Task<bool> validateLoginAsync(SecureDesk.AuthenticateClient.UserCredentials authUser) {
            return base.Channel.validateLoginAsync(authUser);
        }
    }
}
